#!/usr/bin/env python3
"""Generate ticker-about.js for the dynamic /t page.
 - TICKER_ABOUT: per-ticker 'About [Company]' text, extracted verbatim from the
   static /stocks/*.html pages so the two views never diverge.
 - INDUSTRY_ABOUT: one industry overview per AI-Universe basket id (covers all 89)."""
import re, json, glob, os

# Per-ticker About, pulled from the static SEO pages we already wrote.
about = {}
for p in sorted(glob.glob("stocks/*.html")):
    tk = os.path.basename(p)[:-5].upper()
    s = open(p, encoding="utf-8").read()
    m = re.search(r"<h2>About (.*?)</h2>\s*<p>(.*?)</p>", s, re.S)
    if m:
        name = m.group(1).strip()
        text = re.sub(r"\s+", " ", m.group(2)).strip()
        about[tk] = {"name": name, "about": text}

# Industry overview per AI-Universe basket (basket ids from t.html UNI_SHORT).
industry = {
"ai_chips_and_compute": {"heading": "AI chips & compute",
 "text": "This is the semiconductor and compute layer of the AI build-out — the GPUs, custom accelerators, "
 "high-bandwidth memory and processors that train and run models. It is a cyclical, capital-intensive industry split "
 "between fabless designers, foundries that manufacture the chips, and integrated players. AI has become the dominant "
 "demand driver, and the group is unusually exposed to export controls, manufacturing concentration in Taiwan, and sharp "
 "boom-bust capex cycles."},
"ai_software_and_cloud_infrastructure": {"heading": "AI software & cloud infrastructure",
 "text": "These companies provide the cloud platforms, model-serving, databases and infrastructure software that AI "
 "applications run on. Revenue is increasingly tied to AI workloads and consumption-based cloud spending. The economics "
 "favor scale and switching costs, but the group carries high expectations and heavy capital spending on data centers, and "
 "faces questions about how quickly AI usage converts into durable profit."},
"ai_applications_and_data_software": {"heading": "AI applications & data software",
 "text": "This group builds the applications and data tools that put AI to work — analytics, security, developer and "
 "vertical software, plus the data pipelines that feed models. Demand tracks enterprise AI adoption. Many names trade on "
 "growth and the promise of AI-driven expansion, so they can be sensitive to shifts in software spending and to how much "
 "value AI features actually add."},
"chip_equipment_and_ai_hardware": {"heading": "Chip equipment & AI hardware",
 "text": "This layer sells the machines, materials and hardware that make and connect AI systems — semiconductor "
 "manufacturing equipment, networking, optics, memory and servers. It is a concentrated, &ldquo;picks-and-shovels&rdquo; business one "
 "level below the chipmakers. As AI pushes fabs to expand and data centers to scale, demand rises, though the equipment "
 "side is cyclical and heavily exposed to China export restrictions."},
"ai_platforms_internet_and_adtech": {"heading": "AI platforms, internet & adtech",
 "text": "These are large internet, platform and advertising businesses using AI to improve products, recommendations and "
 "ad targeting. They have vast user bases and cash flows, and are among the biggest spenders on AI infrastructure. The AI "
 "link is mostly about defending and extending existing franchises rather than selling AI directly, and results hinge on "
 "advertising cycles and regulation."},
"data_center_power_and_energy": {"heading": "Data-center power & energy",
 "text": "This basket covers the power, energy and physical infrastructure that AI data centers depend on — electricity "
 "generation, grid and cooling, and the operators that host high-density compute. AI's soaring power demand has made this "
 "an unexpectedly central part of the trade. The businesses are capital-intensive and turn on access to cheap, reliable "
 "power, long-term contracts and financing costs."},
"applied_ai_industrial_defense_and_vertical": {"heading": "Applied AI: industrial, defense & vertical",
 "text": "These companies apply AI and autonomy to specific real-world domains — industrials, defense, space, robotics and "
 "other verticals. The link to AI runs through software, sensors, autonomy and the data these systems generate and analyze. "
 "Many are earlier-stage or project-driven, so results can be lumpy and tied to government budgets, contract timing and "
 "execution."},
}

# Drop the non-ticker special pages if they slipped in (aschenbrenner/burry*).
for k in ("ASCHENBRENNER", "BURRY", "BURRY-SHORT-WATCH"):
    about.pop(k, None)

js = ("/* Auto-generated by _gen_about.py — About text mirrors the static /stocks pages. */\n"
      "window.TICKER_ABOUT=" + json.dumps(about, ensure_ascii=False, separators=(",", ":")) + ";\n"
      "window.INDUSTRY_ABOUT=" + json.dumps(industry, ensure_ascii=False, separators=(",", ":")) + ";\n")
open("ticker-about.js", "w", encoding="utf-8").write(js)
print("tickers with About:", len(about), "->", " ".join(sorted(about)))
print("industry baskets:", len(industry))
print("ticker-about.js bytes:", len(js))
